[package]
name = "catgrad"
version = "0.1.0"
edition = "2021"
rust-version = "1.86"
description = "A Categorical Deep Learning Compiler"
license = "MIT"
repository = "https://github.com/hellas-ai/catgrad"
documentation = "https://docs.rs/catgrad"

[dependencies]
open-hypergraphs = "0.2.3"
num-traits = "0.2.19"
gemm = "0.18.2"
half = "2.5.0"
log = "0.4.27"
test-log = "0.2.17"
memmap2 = "0.9.5"
rayon = "1.10.0"
num_cpus = "1.17.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[dev-dependencies]
clap = { version = "4.5.37", features = ["derive"] }
env_logger = "0.11.8"
hf-hub = { version = "0.4.2", default-features = false, features = ["ureq"] }
safetensors = "0.5.3"
tokenizers = { version = "0.21.1", features = ["http"] }
open-hypergraphs-dot = "0.2.1"
graphviz-rust = "0.9.5"
